// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Erweiterung

#include "ui.h"

lv_obj_t * uic_S4Eing;
lv_obj_t * uic_s4WP;
lv_obj_t * uic_s4Bat;
lv_obj_t * uic_S4Netz;
lv_obj_t * uic_S4Bateriestatus;
lv_obj_t * uic_s4Bezug;
lv_obj_t * uic_Bateriestatus;
lv_obj_t * uic_Verbrauch;
lv_obj_t * uic_Eingespeist;
lv_obj_t * uic_WPP;
lv_obj_t * uic_Bat;
lv_obj_t * uic_Netz;
lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Next3 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Netz = NULL;
lv_obj_t * ui_Bat = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_WPP = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Eingespeist = NULL;
lv_obj_t * ui_Verbrauch = NULL;
lv_obj_t * ui_Bateriestatus = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_s4Bezug = NULL;
lv_obj_t * ui_S4Bateriestatus = NULL;
lv_obj_t * ui_S4Netz = NULL;
lv_obj_t * ui_s4Bat = NULL;
lv_obj_t * ui_s4WP = NULL;
lv_obj_t * ui_S4Eing = NULL;
// event funtions
void ui_event_Next3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Screen4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Next3, 107);
    lv_obj_set_height(ui_Next3, 50);
    lv_obj_set_x(ui_Next3, 334);
    lv_obj_set_y(ui_Next3, -204);
    lv_obj_set_align(ui_Next3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Next3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Next3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 331);
    lv_obj_set_y(ui_Label19, -204);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Next");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Netz = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_Netz, 0, 5000);
    lv_bar_set_value(ui_Netz, 2000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Netz, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Netz, 384);
    lv_obj_set_height(ui_Netz, 16);
    lv_obj_set_x(ui_Netz, 36);
    lv_obj_set_y(ui_Netz, 47);

    lv_obj_set_style_bg_color(ui_Netz, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Netz, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bat = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_Bat, 0, 5000);
    lv_bar_set_value(ui_Bat, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bat, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bat, 384);
    lv_obj_set_height(ui_Bat, 16);
    lv_obj_set_x(ui_Bat, 36);
    lv_obj_set_y(ui_Bat, 92);

    lv_obj_set_style_bg_color(ui_Bat, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bat, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -330);
    lv_obj_set_y(ui_Label20, -216);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Netz");

    ui_Label21 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -335);
    lv_obj_set_y(ui_Label21, -162);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Bat");

    ui_WPP = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_WPP, 0, 500);
    lv_bar_set_value(ui_WPP, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WPP, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WPP, 385);
    lv_obj_set_height(ui_WPP, 16);
    lv_obj_set_x(ui_WPP, 36);
    lv_obj_set_y(ui_WPP, 142);

    lv_obj_set_style_bg_color(ui_WPP, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WPP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -341);
    lv_obj_set_y(ui_Label22, -113);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "WP");

    ui_Eingespeist = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_Eingespeist, 0, 50);
    lv_bar_set_value(ui_Eingespeist, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Eingespeist, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Eingespeist, 385);
    lv_obj_set_height(ui_Eingespeist, 16);
    lv_obj_set_x(ui_Eingespeist, 36);
    lv_obj_set_y(ui_Eingespeist, 264);

    lv_obj_set_style_bg_color(ui_Eingespeist, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Eingespeist, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Verbrauch = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_Verbrauch, 0, 50);
    lv_bar_set_value(ui_Verbrauch, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Verbrauch, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Verbrauch, 385);
    lv_obj_set_height(ui_Verbrauch, 16);
    lv_obj_set_x(ui_Verbrauch, 36);
    lv_obj_set_y(ui_Verbrauch, 234);

    lv_obj_set_style_bg_color(ui_Verbrauch, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Verbrauch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bateriestatus = lv_bar_create(ui_Screen4);
    lv_bar_set_value(ui_Bateriestatus, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bateriestatus, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bateriestatus, 385);
    lv_obj_set_height(ui_Bateriestatus, 16);
    lv_obj_set_x(ui_Bateriestatus, 37);
    lv_obj_set_y(ui_Bateriestatus, 335);

    lv_obj_set_style_bg_color(ui_Bateriestatus, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bateriestatus, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -260);
    lv_obj_set_y(ui_Label23, 69);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Batteriestatus	");

    ui_Label24 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -285);
    lv_obj_set_y(ui_Label24, -27);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Bezug/Eing.");

    ui_s4Bezug = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4Bezug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4Bezug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4Bezug, 79);
    lv_obj_set_y(ui_s4Bezug, -5);
    lv_obj_set_align(ui_s4Bezug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4Bezug, "50 KW");

    ui_S4Bateriestatus = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_S4Bateriestatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4Bateriestatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4Bateriestatus, 71);
    lv_obj_set_y(ui_S4Bateriestatus, 100);
    lv_obj_set_align(ui_S4Bateriestatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S4Bateriestatus, "100 %");

    ui_S4Netz = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_S4Netz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4Netz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4Netz, 101);
    lv_obj_set_y(ui_S4Netz, -190);
    lv_obj_set_align(ui_S4Netz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S4Netz, "5000 Watt");

    ui_s4Bat = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4Bat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4Bat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4Bat, 99);
    lv_obj_set_y(ui_s4Bat, -141);
    lv_obj_set_align(ui_s4Bat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4Bat, "5000 Watt");

    ui_s4WP = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_s4WP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s4WP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s4WP, 99);
    lv_obj_set_y(ui_s4WP, -86);
    lv_obj_set_align(ui_s4WP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_s4WP, "5000 Watt");

    ui_S4Eing = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_S4Eing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4Eing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4Eing, 79);
    lv_obj_set_y(ui_S4Eing, 30);
    lv_obj_set_align(ui_S4Eing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S4Eing, "50 KW");

    lv_obj_add_event_cb(ui_Next3, ui_event_Next3, LV_EVENT_ALL, NULL);
    uic_Netz = ui_Netz;
    uic_Bat = ui_Bat;
    uic_WPP = ui_WPP;
    uic_Eingespeist = ui_Eingespeist;
    uic_Verbrauch = ui_Verbrauch;
    uic_Bateriestatus = ui_Bateriestatus;
    uic_s4Bezug = ui_s4Bezug;
    uic_S4Bateriestatus = ui_S4Bateriestatus;
    uic_S4Netz = ui_S4Netz;
    uic_s4Bat = ui_s4Bat;
    uic_s4WP = ui_s4WP;
    uic_S4Eing = ui_S4Eing;

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Next3 = NULL;
    ui_Label19 = NULL;
    uic_Netz = NULL;
    ui_Netz = NULL;
    uic_Bat = NULL;
    ui_Bat = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    uic_WPP = NULL;
    ui_WPP = NULL;
    ui_Label22 = NULL;
    uic_Eingespeist = NULL;
    ui_Eingespeist = NULL;
    uic_Verbrauch = NULL;
    ui_Verbrauch = NULL;
    uic_Bateriestatus = NULL;
    ui_Bateriestatus = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    uic_s4Bezug = NULL;
    ui_s4Bezug = NULL;
    uic_S4Bateriestatus = NULL;
    ui_S4Bateriestatus = NULL;
    uic_S4Netz = NULL;
    ui_S4Netz = NULL;
    uic_s4Bat = NULL;
    ui_s4Bat = NULL;
    uic_s4WP = NULL;
    ui_s4WP = NULL;
    uic_S4Eing = NULL;
    ui_S4Eing = NULL;

}
