// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Erweiterung

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_lblip;
extern lv_obj_t * ui_Grafik;
extern lv_obj_t * ui_Preis;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_kwheute;
extern void ui_event_Next(lv_event_t * e);
extern lv_obj_t * ui_Next;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_tageskosten;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_lblip;
extern lv_obj_t * uic_Grafik;
extern lv_obj_t * uic_Preis;
extern lv_obj_t * uic_kwheute;
extern lv_obj_t * uic_Next;
extern lv_obj_t * uic_Label5;
extern lv_obj_t * uic_tageskosten;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

