// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Erweiterung

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Grafikverbrauch;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_aktuell;
extern void ui_event_Next1(lv_event_t * e);
extern lv_obj_t * ui_Next1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_kwproduziert;
extern lv_obj_t * ui_kwverbraucht;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_baterieleistung;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Grafikverbrauch;
extern lv_obj_t * uic_aktuell;
extern lv_obj_t * uic_kwproduziert;
extern lv_obj_t * uic_kwverbraucht;
extern lv_obj_t * uic_baterieleistung;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

