// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Erweiterung

#include "ui.h"

lv_obj_t * uic_Grafik;
lv_obj_t * uic_tageskosten;
lv_obj_t * uic_Label5;
lv_obj_t * uic_Next;
lv_obj_t * uic_kwheute;
lv_obj_t * uic_Preis;
lv_obj_t * uic_lblip;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_lblip = NULL;
lv_obj_t * ui_Preis = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_kwheute = NULL;
lv_obj_t * ui_Next = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_tageskosten = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Grafik = NULL;
// event funtions
void ui_event_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -330);
    lv_obj_set_y(ui_Label1, -206);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Akt. Preis:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblip = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblip, 305);
    lv_obj_set_y(ui_lblip, 209);
    lv_obj_set_align(ui_lblip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblip, "192.168.2.xxx");
    lv_obj_set_style_text_font(ui_lblip, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preis = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Preis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preis, -220);
    lv_obj_set_y(ui_Preis, -206);
    lv_obj_set_align(ui_Preis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Preis, "15.23");
    lv_obj_set_style_text_font(ui_Preis, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -13);
    lv_obj_set_y(ui_Label2, -211);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "KW heute:");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kwheute = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_kwheute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kwheute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kwheute, 118);
    lv_obj_set_y(ui_kwheute, -210);
    lv_obj_set_align(ui_kwheute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kwheute, "99999");
    lv_obj_set_style_text_font(ui_kwheute, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Next, 107);
    lv_obj_set_height(ui_Next, 50);
    lv_obj_set_x(ui_Next, 334);
    lv_obj_set_y(ui_Next, -204);
    lv_obj_set_align(ui_Next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Next, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Next, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 331);
    lv_obj_set_y(ui_Label5, -204);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Next");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -146);
    lv_obj_set_y(ui_Label7, -205);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Ct / KW");

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -333);
    lv_obj_set_y(ui_Label8, -166);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Tag Ges.:");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tageskosten = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tageskosten, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tageskosten, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tageskosten, -221);
    lv_obj_set_y(ui_tageskosten, -168);
    lv_obj_set_align(ui_tageskosten, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tageskosten, "15.23");
    lv_obj_set_style_text_font(ui_tageskosten, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -158);
    lv_obj_set_y(ui_Label3, -162);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "EUR");

    ui_Grafik = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Grafik, 691);
    lv_obj_set_height(ui_Grafik, 255);
    lv_obj_set_x(ui_Grafik, 0);
    lv_obj_set_y(ui_Grafik, 13);
    lv_obj_set_align(ui_Grafik, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Grafik, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Grafik, 96);
    lv_chart_set_range(ui_Grafik, LV_CHART_AXIS_PRIMARY_Y, -10, 30);
    lv_chart_set_range(ui_Grafik, LV_CHART_AXIS_SECONDARY_Y, 0, 500);
    lv_chart_set_div_line_count(ui_Grafik, 6, 24);
    lv_chart_set_axis_tick(ui_Grafik, LV_CHART_AXIS_PRIMARY_X, 10, 6, 24, 1, true, 50);
    lv_chart_set_axis_tick(ui_Grafik, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Grafik, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 6, 2, true, 25);

    lv_obj_add_event_cb(ui_Next, ui_event_Next, LV_EVENT_ALL, NULL);
    uic_lblip = ui_lblip;
    uic_Preis = ui_Preis;
    uic_kwheute = ui_kwheute;
    uic_Next = ui_Next;
    uic_Label5 = ui_Label5;
    uic_tageskosten = ui_tageskosten;
    uic_Grafik = ui_Grafik;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    uic_lblip = NULL;
    ui_lblip = NULL;
    uic_Preis = NULL;
    ui_Preis = NULL;
    ui_Label2 = NULL;
    uic_kwheute = NULL;
    ui_kwheute = NULL;
    uic_Next = NULL;
    ui_Next = NULL;
    uic_Label5 = NULL;
    ui_Label5 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    uic_tageskosten = NULL;
    ui_tageskosten = NULL;
    ui_Label3 = NULL;
    uic_Grafik = NULL;
    ui_Grafik = NULL;

}
