// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Erweiterung

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TempWarmwasser;
extern void ui_event_Next2(lv_event_t * e);
extern lv_obj_t * ui_Next2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_WPTag;
extern lv_obj_t * ui_WPNacht;
extern lv_obj_t * ui_WPWatt;
extern lv_obj_t * ui_WPStatus;
extern void ui_event_WPmanuel(lv_event_t * e);
extern lv_obj_t * ui_WPmanuel;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TempWarmwasser;
extern lv_obj_t * uic_WPTag;
extern lv_obj_t * uic_WPNacht;
extern lv_obj_t * uic_WPWatt;
extern lv_obj_t * uic_WPStatus;
extern lv_obj_t * uic_WPmanuel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

