// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Erweiterung

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_Next3(lv_event_t * e);
extern lv_obj_t * ui_Next3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Netz;
extern lv_obj_t * ui_Bat;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_WPP;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Eingespeist;
extern lv_obj_t * ui_Verbrauch;
extern lv_obj_t * ui_Bateriestatus;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_s4Bezug;
extern lv_obj_t * ui_S4Bateriestatus;
extern lv_obj_t * ui_S4Netz;
extern lv_obj_t * ui_s4Bat;
extern lv_obj_t * ui_s4WP;
extern lv_obj_t * ui_S4Eing;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Netz;
extern lv_obj_t * uic_Bat;
extern lv_obj_t * uic_WPP;
extern lv_obj_t * uic_Eingespeist;
extern lv_obj_t * uic_Verbrauch;
extern lv_obj_t * uic_Bateriestatus;
extern lv_obj_t * uic_s4Bezug;
extern lv_obj_t * uic_S4Bateriestatus;
extern lv_obj_t * uic_S4Netz;
extern lv_obj_t * uic_s4Bat;
extern lv_obj_t * uic_s4WP;
extern lv_obj_t * uic_S4Eing;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

