// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Erweiterung

#include "ui.h"

lv_obj_t * uic_kwverbraucht;
lv_obj_t * uic_kwproduziert;
lv_obj_t * uic_aktuell;
lv_obj_t * uic_Grafikverbrauch;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Grafikverbrauch = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_aktuell = NULL;
lv_obj_t * ui_Next1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_kwproduziert = NULL;
lv_obj_t * ui_kwverbraucht = NULL;
// event funtions
void ui_event_Next1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Grafikverbrauch = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_Grafikverbrauch, 691);
    lv_obj_set_height(ui_Grafikverbrauch, 331);
    lv_obj_set_x(ui_Grafikverbrauch, -2);
    lv_obj_set_y(ui_Grafikverbrauch, 33);
    lv_obj_set_align(ui_Grafikverbrauch, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Grafikverbrauch, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Grafikverbrauch, 60);
    lv_chart_set_range(ui_Grafikverbrauch, LV_CHART_AXIS_PRIMARY_Y, 0, 3000);
    lv_chart_set_range(ui_Grafikverbrauch, LV_CHART_AXIS_SECONDARY_Y, 0, 3000);
    lv_chart_set_div_line_count(ui_Grafikverbrauch, 5, 7);
    lv_chart_set_axis_tick(ui_Grafikverbrauch, LV_CHART_AXIS_PRIMARY_X, 20, 5, 7, 10, true, 20);
    lv_chart_set_axis_tick(ui_Grafikverbrauch, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 9, 2, true, 50);
    lv_chart_set_axis_tick(ui_Grafikverbrauch, LV_CHART_AXIS_SECONDARY_Y, 5, 5, 9, 2, true, 25);

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -327);
    lv_obj_set_y(ui_Label4, -212);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Aktuell:");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aktuell = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_aktuell, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aktuell, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aktuell, -547);
    lv_obj_set_y(ui_aktuell, -213);
    lv_obj_set_align(ui_aktuell, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_aktuell, "9999");
    lv_obj_set_style_text_font(ui_aktuell, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Next1, 107);
    lv_obj_set_height(ui_Next1, 50);
    lv_obj_set_x(ui_Next1, 334);
    lv_obj_set_y(ui_Next1, -204);
    lv_obj_set_align(ui_Next1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Next1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Next1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 331);
    lv_obj_set_y(ui_Label6, -204);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Next");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -101);
    lv_obj_set_y(ui_Label9, -212);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Watt	");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 96);
    lv_obj_set_y(ui_Label10, -212);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Einges.");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 106);
    lv_obj_set_y(ui_Label11, -172);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Verb.");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kwproduziert = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kwproduziert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kwproduziert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kwproduziert, 190);
    lv_obj_set_y(ui_kwproduziert, -213);
    lv_obj_set_align(ui_kwproduziert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kwproduziert, "9999");
    lv_obj_set_style_text_font(ui_kwproduziert, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kwverbraucht = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kwverbraucht, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kwverbraucht, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kwverbraucht, 192);
    lv_obj_set_y(ui_kwverbraucht, -171);
    lv_obj_set_align(ui_kwverbraucht, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kwverbraucht, "9999");
    lv_obj_set_style_text_font(ui_kwverbraucht, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Next1, ui_event_Next1, LV_EVENT_ALL, NULL);
    uic_Grafikverbrauch = ui_Grafikverbrauch;
    uic_aktuell = ui_aktuell;
    uic_kwproduziert = ui_kwproduziert;
    uic_kwverbraucht = ui_kwverbraucht;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    uic_Grafikverbrauch = NULL;
    ui_Grafikverbrauch = NULL;
    ui_Label4 = NULL;
    uic_aktuell = NULL;
    ui_aktuell = NULL;
    ui_Next1 = NULL;
    ui_Label6 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    uic_kwproduziert = NULL;
    ui_kwproduziert = NULL;
    uic_kwverbraucht = NULL;
    ui_kwverbraucht = NULL;

}
