// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Erweiterung

#include "ui.h"

lv_obj_t * uic_GrafikWW;
lv_obj_t * uic_WPStatus;
lv_obj_t * uic_WPWatt;
lv_obj_t * uic_WPNacht;
lv_obj_t * uic_WPTag;
lv_obj_t * uic_TempWarmwasser;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_TempWarmwasser = NULL;
lv_obj_t * ui_Next2 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_WPTag = NULL;
lv_obj_t * ui_WPNacht = NULL;
lv_obj_t * ui_WPWatt = NULL;
lv_obj_t * ui_WPStatus = NULL;
lv_obj_t * ui_GrafikWW = NULL;
// event funtions
void ui_event_Next2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -309);
    lv_obj_set_y(ui_Label12, -19);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "WP Status:");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempWarmwasser = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_TempWarmwasser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempWarmwasser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempWarmwasser, -529);
    lv_obj_set_y(ui_TempWarmwasser, -213);
    lv_obj_set_align(ui_TempWarmwasser, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TempWarmwasser, "0");
    lv_obj_set_style_text_font(ui_TempWarmwasser, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Next2, 107);
    lv_obj_set_height(ui_Next2, 50);
    lv_obj_set_x(ui_Next2, 334);
    lv_obj_set_y(ui_Next2, -204);
    lv_obj_set_align(ui_Next2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Next2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Next2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 331);
    lv_obj_set_y(ui_Label13, -204);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Next");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -86);
    lv_obj_set_y(ui_Label14, -213);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Grad");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -329);
    lv_obj_set_y(ui_Label15, -172);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "WP Tag:");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -311);
    lv_obj_set_y(ui_Label16, -92);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "WP Nacht:");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -295);
    lv_obj_set_y(ui_Label17, -213);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Warmwasser:");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -317);
    lv_obj_set_y(ui_Label18, 23);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "WP Watt:");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WPTag = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WPTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WPTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WPTag, 21);
    lv_obj_set_y(ui_WPTag, -134);
    lv_obj_set_align(ui_WPTag, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WPTag, "00:00 01:00 02:00 04:00 00:00 01:00 02:00 04:00");
    lv_obj_set_style_text_font(ui_WPTag, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WPNacht = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WPNacht, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WPNacht, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WPNacht, 17);
    lv_obj_set_y(ui_WPNacht, -60);
    lv_obj_set_align(ui_WPNacht, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WPNacht, "00:00 01:00 02:00 04:00 00:00 01:00 02:00 04:00");
    lv_obj_set_style_text_font(ui_WPNacht, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WPWatt = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WPWatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WPWatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WPWatt, -532);
    lv_obj_set_y(ui_WPWatt, 23);
    lv_obj_set_align(ui_WPWatt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_WPWatt, "0");
    lv_obj_set_style_text_font(ui_WPWatt, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WPStatus = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WPStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WPStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WPStatus, -139);
    lv_obj_set_y(ui_WPStatus, -19);
    lv_obj_set_align(ui_WPStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WPStatus, "WP Status:");
    lv_obj_set_style_text_font(ui_WPStatus, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrafikWW = lv_chart_create(ui_Screen3);
    lv_obj_set_width(ui_GrafikWW, 691);
    lv_obj_set_height(ui_GrafikWW, 145);
    lv_obj_set_x(ui_GrafikWW, -10);
    lv_obj_set_y(ui_GrafikWW, 128);
    lv_obj_set_align(ui_GrafikWW, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_GrafikWW, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_GrafikWW, 96);
    lv_chart_set_range(ui_GrafikWW, LV_CHART_AXIS_PRIMARY_Y, 0, 80);
    lv_chart_set_range(ui_GrafikWW, LV_CHART_AXIS_SECONDARY_Y, 0, 80);
    lv_chart_set_div_line_count(ui_GrafikWW, 8, 24);
    lv_chart_set_axis_tick(ui_GrafikWW, LV_CHART_AXIS_PRIMARY_X, 10, 6, 24, 1, true, 80);
    lv_chart_set_axis_tick(ui_GrafikWW, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 80);
    lv_chart_set_axis_tick(ui_GrafikWW, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);

    lv_obj_add_event_cb(ui_Next2, ui_event_Next2, LV_EVENT_ALL, NULL);
    uic_TempWarmwasser = ui_TempWarmwasser;
    uic_WPTag = ui_WPTag;
    uic_WPNacht = ui_WPNacht;
    uic_WPWatt = ui_WPWatt;
    uic_WPStatus = ui_WPStatus;
    uic_GrafikWW = ui_GrafikWW;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label12 = NULL;
    uic_TempWarmwasser = NULL;
    ui_TempWarmwasser = NULL;
    ui_Next2 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    uic_WPTag = NULL;
    ui_WPTag = NULL;
    uic_WPNacht = NULL;
    ui_WPNacht = NULL;
    uic_WPWatt = NULL;
    ui_WPWatt = NULL;
    uic_WPStatus = NULL;
    ui_WPStatus = NULL;
    uic_GrafikWW = NULL;
    ui_GrafikWW = NULL;

}
